# Generated by Django 5.2.4 on 2025-07-15 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approved_me", "Approved Me"),
                            ("hot", "Hot"),
                            ("maybe", "Maybe"),
                            ("liked", "Liked"),
                            ("liked_me", "Liked Me"),
                            ("matched", "Matched"),
                            ("saved", "Saved"),
                            ("not_approved", "Not Approved"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tagged_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tag",
                "verbose_name_plural": "User Tags",
                "unique_together": {("user", "tagged_user", "tag")},
            },
        ),
    ]
