# Generated by Django 5.0.2 on 2025-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_usertag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
