# Generated by Django 5.0.2 on 2025-08-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_name",
            field=models.CharField(
                blank=True,
                help_text="Short name/identifier for the question",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Question number for ordering", null=True
            ),
        ),
    ]
