# Generated by Django 5.0.2 on 2025-08-23 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_question_question_name_question_question_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group_name",
            field=models.CharField(
                blank=True,
                help_text="Group/category name for the question",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Whether the question is approved for use"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="open_to_all_looking_for",
            field=models.BooleanField(
                default=False, help_text="Whether I'm open to all options in a partner"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="open_to_all_me",
            field=models.BooleanField(
                default=False, help_text="Whether I'm open to all options"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="skip_looking_for",
            field=models.BooleanField(
                default=False,
                help_text="Whether to skip asking about what I'm looking for",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="skip_me",
            field=models.BooleanField(
                default=False, help_text="Whether to skip asking about me"
            ),
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Answer value (1, 2, 3, 4, 5)", max_length=10
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(help_text="Answer text", max_length=500),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the answer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("question", "value")},
            },
        ),
    ]
