# Generated by Django 5.0.2 on 2025-08-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_question_group_name_question_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="looking_for_multiplier",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="me_multiplier",
        ),
        migrations.AddField(
            model_name="useranswer",
            name="looking_for_importance",
            field=models.PositiveIntegerField(
                default=1, help_text="Importance level for this answer"
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="me_importance",
            field=models.PositiveIntegerField(
                default=1, help_text="Importance level for this answer"
            ),
        ),
    ]
