# Generated by Django 5.0.2 on 2025-08-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_multiplier_to_importance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="from_location",
            field=models.CharField(
                blank=True,
                help_text="Where the user is originally from",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="live",
            field=models.CharField(
                blank=True,
                help_text="Where the user currently lives",
                max_length=100,
                null=True,
            ),
        ),
    ]
