# Generated by Django 5.0.2 on 2025-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_add_from_location_and_rename_city_to_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Group number for organizing questions into categories",
                null=True,
            ),
        ),
    ]
