# Generated by Django 5.0.2 on 2025-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_add_group_number_to_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question represents a group/category",
            ),
        ),
    ]
