# Generated by Django 5.0.2 on 2025-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_add_is_group_to_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tagline",
            field=models.CharField(
                blank=True, help_text="Short tagline", max_length=40
            ),
        ),
    ]
