# Generated by Django 5.0.2 on 2025-09-15 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_user_tagline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.AddField(
            model_name="question",
            name="is_mandatory",
            field=models.BooleanField(
                default=False, help_text="Whether this is a mandatory question (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this question",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_required_for_match",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is required for matching",
            ),
        ),
    ]
