# Generated by Django 5.0.2 on 2025-09-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_set_mandatory_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group_name_text",
            field=models.TextField(
                blank=True, help_text="Detailed description or text for the group"
            ),
        ),
    ]
