# Generated by Django 5.0.2 on 2025-09-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_question_group_name_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("four", "Four"),
                    ("grouped", "Grouped"),
                    ("double", "Double"),
                    ("triple", "Triple"),
                ],
                default="basic",
                help_text="Type of question",
                max_length=20,
            ),
        ),
    ]
