# Generated by Django 5.0.2 on 2025-09-28 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_question_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Controls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjust",
                    models.FloatField(
                        default=5.0, help_text="Adjustment factor for calculations"
                    ),
                ),
                (
                    "exponent",
                    models.FloatField(
                        default=2.0, help_text="Exponent value for calculations"
                    ),
                ),
                (
                    "ota",
                    models.FloatField(
                        default=0.5,
                        help_text="OTA (Open To All) weight factor",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Control Settings",
                "verbose_name_plural": "Control Settings",
            },
        ),
    ]
