# Generated by Django 5.0.2 on 2025-09-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_add_controls_model"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="compatibility",
            index=models.Index(
                fields=["user1", "-overall_compatibility"],
                name="compatibility_user1_score",
            ),
        ),
        migrations.AddIndex(
            model_name="compatibility",
            index=models.Index(
                fields=["user2", "-overall_compatibility"],
                name="compatibility_user2_score",
            ),
        ),
        migrations.AddIndex(
            model_name="compatibility",
            index=models.Index(
                fields=["-overall_compatibility"], name="compatibility_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compatibility",
            index=models.Index(
                fields=["user1", "user2"], name="compatibility_pair_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compatibility",
            index=models.Index(
                fields=["last_calculated"], name="compatibility_calculated_idx"
            ),
        ),
    ]
