# Generated by Django 5.0.2 on 2025-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_add_compatibility_indexes"),
    ]

    operations = [
        # Add index on question_number for fast filtering
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_number'], name='question_qnum_idx'),
        ),
        # Add composite index on (question_number, group_number) for sorting
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_number', 'group_number'], name='question_qnum_gnum_idx'),
        ),
        # Add index on is_approved for filtering approved questions
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_approved'], name='question_approved_idx'),
        ),
        # Add composite index for approved + question_number (common query pattern)
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_approved', 'question_number'], name='question_approved_qnum_idx'),
        ),
    ]
