# Generated by Django 5.0.2 on 2025-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_add_question_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="question_qnum_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_qnum_gnum_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_approved_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_approved_qnum_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userresult",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userresult",
            name="tag",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("approved_me", "Approved Me"),
                    ("hot", "Hot"),
                    ("maybe", "Maybe"),
                    ("like", "Like"),
                    ("liked", "Liked"),
                    ("liked_me", "Liked Me"),
                    ("matched", "Matched"),
                    ("save", "Save"),
                    ("saved", "Saved"),
                    ("not_approved", "Not Approved"),
                    ("hide", "Hide"),
                    ("hidden", "Hidden"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userresult",
            unique_together={("user", "result_user", "tag")},
        ),
        migrations.AddIndex(
            model_name="userresult",
            index=models.Index(
                fields=["user", "result_user"], name="userresult_user_pair_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userresult",
            index=models.Index(fields=["user", "tag"], name="userresult_user_tag_idx"),
        ),
    ]
