# Generated by Django 5.0.2 on 2025-10-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_remove_question_question_qnum_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("total_approves", models.IntegerField(default=0)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_matches", models.IntegerField(default=0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_metrics",
                "ordering": ["-date"],
            },
        ),
    ]
