# Generated by Django 5.0.2 on 2025-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_dailymetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="picturemoderation",
            name="picture_url",
            field=models.URLField(
                blank=True,
                help_text="Azure Blob Storage URL for the picture",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="picturemoderation",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="moderation_queue/"
            ),
        ),
    ]
