# Generated by Django 5.0.2 on 2025-10-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_picturemoderation_picture_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestrictedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        db_index=True,
                        help_text="Restricted word (stored in lowercase)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="high",
                        help_text="Severity level of the restriction",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this restriction is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "restricted_words",
                "ordering": ["word"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "word"], name="restricted_word_active_idx"
                    )
                ],
            },
        ),
    ]
