# Generated by Django 5.0.2 on 2025-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_restrictedword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False, help_text="Grants access to internal dashboard features."
            ),
        ),
    ]
