# Generated by Django 5.0.2 on 2025-11-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_message_table_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("like", "Like"),
                    ("match", "Match"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
