# Generated by Django 5.0.2 on 2025-11-26 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_notification_note_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_seen",
            new_name="last_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_online",
        ),
    ]
