# Generated by Django 5.0.2 on 2025-12-31 18:29

from django.db import migrations, models
from django.db import transaction


# No data cleanup needed - duplicate question_numbers are allowed for grouped questions


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_rename_last_seen_user_last_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionNumberCounter",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Last allocated question number"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Number Counter",
                "verbose_name_plural": "Question Number Counter",
                "db_table": "question_number_counter",
            },
        ),
        # Note: No unique constraint on question_number because grouped questions
        # share the same question_number (with different group_number values)
    ]
