# Generated by Django 5.0.2 on 2026-01-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_cleanup_question_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="compatibility",
            name="required_compatible_with_me",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="required_completeness_ratio",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="required_im_compatible_with",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="required_mutual_questions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="required_overall_compatibility",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
