# Generated by Django 5.0.2 on 2026-01-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_add_required_compatibility_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="compatibility",
            name="user1_required_completeness",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Of user2's answered required questions, what % did user1 also answer?",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="user2_required_completeness",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Of user1's answered required questions, what % did user2 also answer?",
                max_digits=4,
            ),
        ),
    ]
