# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_compatibility_user1_required_completeness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="is_required_for_me",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user requires this question to be answered for matching (per-user required)",
            ),
        ),
    ]
