# Generated by Django 5.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0034_set_is_required_for_me_from_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequiredQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="required_by_users", to="api.question")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="required_questions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "api_userrequiredquestion",
                "verbose_name": "User required question",
                "verbose_name_plural": "User required questions",
            },
        ),
        migrations.AddConstraint(
            model_name="userrequiredquestion",
            constraint=models.UniqueConstraint(fields=("user", "question"), name="api_userrequiredquestion_user_question_uniq"),
        ),
    ]
