# Generated by Django 5.0.2 on 2026-03-09 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_compatibility_their_required_compatibility"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userrequiredquestion",
            name="api_userrequiredquestion_user_question_uniq",
        ),
        migrations.AlterUniqueTogether(
            name="userrequiredquestion",
            unique_together={("user", "question")},
        ),
    ]
