# Generated by Django 5.0.2 on 2026-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0039_remove_userrequiredquestion_api_userrequiredquestion_user_question_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restriction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="restriction_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in days (for temporary)", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restriction_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="restriction_type",
            field=models.CharField(
                blank=True, help_text="temporary or permanent", max_length=20, null=True
            ),
        ),
    ]
