# Generated by Django 5.0.2 on 2026-03-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_add_restriction_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreport",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("fake_profile", "Fake Profile"),
                    ("inappropriate_photos", "Inappropriate Photos"),
                    ("harassment", "Harassment"),
                    ("spam", "Spam"),
                    ("offensive_language", "Offensive Language"),
                    ("scam_fraud", "Scam / Fraud"),
                    ("underage_user", "Underage User"),
                    ("other", "Other"),
                    ("admin_restriction", "Admin Restriction"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
