# Generated by Django 5.2.4 on 2026-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_userreport_reason_category_alter_userreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restriction_reason_detail',
            field=models.TextField(blank=True, default='', help_text='Additional description for the restriction reason'),
        ),
    ]
