# Generated by Django 5.2.4 on 2026-04-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_restriction_reason_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_code_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_codes',
                'indexes': [models.Index(fields=['code', 'is_used'], name='invite_code_code_e4d3bc_idx')],
            },
        ),
    ]
