# Generated by Django 5.0.2 on 2026-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_invitecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_answers_for_likes",
            field=models.BooleanField(
                default=False,
                help_text="If true, other users can only like this user after answering all of this user's required questions",
            ),
        ),
    ]
