# Generated by Django 5.0.2 on 2026-05-10 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_user_require_answers_for_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPicture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = primary thumbnail"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("user", "order")},
            },
        ),
    ]
