# Generated by Django 5.0.2 on 2026-05-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0047_post_postcomment_posthashtag_postimage_postreaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all", "Everyone"),
                    ("approved", "Approved"),
                    ("liked", "Liked"),
                    ("matched", "Matches"),
                ],
                default="all",
                max_length=16,
            ),
        ),
    ]
