# Generated by Django 5.0.2 on 2026-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_post_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feed_visibility_bio",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("all", "Everyone"),
                    ("approved", "Approved"),
                    ("liked", "Liked"),
                    ("matched", "Matched"),
                ],
                default="all",
                help_text="Who can see this user's bio-update activities in the feed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="feed_visibility_photo",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("all", "Everyone"),
                    ("approved", "Approved"),
                    ("liked", "Liked"),
                    ("matched", "Matched"),
                ],
                default="all",
                help_text="Who can see this user's photo-added activities in the feed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="feed_visibility_question",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("all", "Everyone"),
                    ("approved", "Approved"),
                    ("liked", "Liked"),
                    ("matched", "Matched"),
                ],
                default="all",
                help_text="Who can see this user's question-answered activities in the feed.",
                max_length=16,
            ),
        ),
    ]
