# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_user_feed_visibility_bio_user_feed_visibility_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="share_answers",
            field=models.BooleanField(
                default=False,
                help_text="If true, users who can view this user's shared answers can also see their looking-for answers.",
            ),
        ),
    ]
