# Generated by Django 5.0.2 on 2026-06-01 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


PROMPT_SEED_DATA = [
    ("The way to win me over is...", "dating"),
    ("My simple pleasures...", "about"),
    ("I go crazy for...", "fun"),
    ("Together, we could...", "dating"),
    ("My most irrational fear...", "deeper"),
    ("We'll get along if...", "values"),
    ("I'm looking for...", "values"),
    ("This year, I really want to...", "lifestyle"),
    ("My typical Sunday is...", "lifestyle"),
    ("A life goal of mine...", "values"),
    ("My greatest strength...", "about"),
    ("Dating me is like...", "deeper"),
    ("I'm convinced that...", "opinion"),
    ("I want someone who...", "values"),
    ("Unusual skills...", "about"),
    ("The key to my heart is...", "dating"),
    ("First round is on me if...", "dating"),
    ("What if I told you that...", "fun"),
    ("I'm weirdly attracted to...", "fun"),
    ("My love language is...", "values"),
    ("All I ask is that you...", "values"),
    ("I'll fall for you if...", "dating"),
    ("I won't shut up about...", "opinion"),
    ("The one thing you should know about me is...", "deeper"),
    ("I bet you can't...", "fun"),
    ("A shower thought I recently had...", "fun"),
    ("Green flags I look for...", "values"),
    ("We're the same type of weird if...", "interactive"),
    ("My real-life superpower...", "about"),
    ("When no one is watching, I...", "about"),
    ("My personal hell is...", "fun"),
    ("What makes a relationship great is...", "values"),
    ("I am hoping you...", "values"),
    ("I guarantee that you...", "fun"),
    ("The quickest way to my heart...", "dating"),
    ("I get way too excited about...", "about"),
    ("After work, you can find me...", "lifestyle"),
    ("I am a great +1 because...", "about"),
    ("If I were president...", "fun"),
    ("Two truths and a lie...", "interactive"),
    ("A non-negotiable...", "values"),
    ("My zombie apocalypse plan is...", "fun"),
    ("I'm known for...", "about"),
    ("It's meant to be if...", "dating"),
    ("The world would be a better place with more...", "opinion"),
    ("A pro and con of dating me...", "deeper"),
    ("I will never shut up about...", "opinion"),
    ("Never have I ever...", "interactive"),
    ("Swipe right if...", "interactive"),
    ("A fun fact I'm obsessed with...", "about"),
    ("As a child, I was really into...", "about"),
    ("Something I learned way later than I should have...", "deeper"),
    ("Perfect first date...", "dating"),
    ("I'm really nerdy about...", "about"),
    ("Favorite quality in a person...", "values"),
]


def seed_prompt_templates(apps, schema_editor):
    PromptTemplate = apps.get_model("api", "PromptTemplate")
    for order, (text, category) in enumerate(PROMPT_SEED_DATA):
        PromptTemplate.objects.update_or_create(
            text=text,
            defaults={
                "category": category,
                "order": order,
                "is_active": True,
            },
        )


def unseed_prompt_templates(apps, schema_editor):
    PromptTemplate = apps.get_model("api", "PromptTemplate")
    PromptTemplate.objects.filter(text__in=[text for text, _ in PROMPT_SEED_DATA]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_add_other_ethnicity_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=160, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("about", "About You"),
                            ("values", "Values"),
                            ("lifestyle", "Lifestyle"),
                            ("fun", "Fun"),
                            ("dating", "Dating"),
                            ("deeper", "Deeper"),
                            ("opinion", "Opinion"),
                            ("interactive", "Interactive"),
                        ],
                        default="about",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "text"],
            },
        ),
        migrations.RunPython(seed_prompt_templates, unseed_prompt_templates),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("like", "Like"),
                    ("match", "Match"),
                    ("note", "Note"),
                    ("prompt_poll", "Prompt Poll"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PromptPollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_option_index", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="related_prompt_poll_vote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.promptpollvote",
            ),
        ),
        migrations.CreateModel(
            name="UserProfilePrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("written", "Written"),
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("poll", "Poll"),
                        ],
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("written_answer", models.CharField(blank=True, max_length=150)),
                ("media_url", models.URLField(blank=True, max_length=1000)),
                (
                    "media_duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("poll_options", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_prompts",
                        to="api.prompttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="promptpollvote",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_votes",
                to="api.userprofileprompt",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofileprompt",
            index=models.Index(
                fields=["user", "is_active", "order"], name="profile_prompt_user_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprofileprompt",
            unique_together={("user", "order")},
        ),
        migrations.AddIndex(
            model_name="promptpollvote",
            index=models.Index(
                fields=["prompt", "voter"], name="poll_vote_prompt_voter_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptpollvote",
            index=models.Index(
                fields=["prompt", "-updated_at"], name="poll_vote_prompt_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptpollvote",
            unique_together={("prompt", "voter")},
        ),
    ]
