# Generated by Django 5.2.4 on 2026-07-26 04:04

from django.db import migrations, models
from django.db.models.functions import Left, Length


def truncate_overlong_text(apps, schema_editor):
    """Trim values written under the old, longer limits.

    me_note is a CharField, so narrowing varchar(280) -> varchar(160) fails on
    Postgres unless the data already fits. bio is a TextField (no DB constraint)
    but an over-long value would make every later profile save fail validation,
    so it gets trimmed too. Post bodies are left alone -- they are only revalidated
    when the author edits them.
    """
    UserAnswer = apps.get_model("api", "UserAnswer")
    User = apps.get_model("api", "User")

    UserAnswer.objects.annotate(note_len=Length("me_note")).filter(
        note_len__gt=160
    ).update(me_note=Left("me_note", 160))

    User.objects.annotate(bio_len=Length("bio")).filter(bio_len__gt=280).update(
        bio=Left("bio", 280)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0067_answer_note_and_note_visibility"),
    ]

    operations = [
        migrations.RunPython(truncate_overlong_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="me_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text note the user attaches to their Me answer; visibility governed by User.note_visibility.",
                max_length=160,
            ),
        ),
    ]
